### ISSUE TITLE
Get array of breadcrumbs

### ISSUE THREAD

**Issue by decadence** [mtekk/Breadcrumb-NavXT#172]
Hello.
Is there any way to get array of breadcrumbs which is generated for current page for custom output?

I was trying
```php
global $breadcrumb_navxt;
$breadcrumb_navxt->breadcrumb_trail;
```
But that is protected property and if I make it public it's null anyway. It will be filled only after `bcn_display` call.
Can you provide easy way to get it?

**Comment by mtekk** [comment]
Can you share some information regarding the problem you are trying to solve? There are several ways to interact with the breadcrumb trail and knowing more about your problem will help me make a recommendation.

**Comment by mtekk** [comment]
While I can appreciate what you want to do, I have to warn that this is something that is fraught with danger (and if you distribute this, will cause user confusion if the admin interface is available). The way this would be traditionally done is to manually instantiate `bcn_breadcrumb_trail` and then modify the `opts` array as you desire. Then, run `fill()` and lastly, the appropriate `display()` function. However, this interface with the `bcn_breadcrumb_trail` is not guaranteed, and changes will be made in the upcoming 6.0 release.

If setting portability is your ultimate goal, there is a settings export/import interface within the setting page. The benefit of this is it will run the settings through the update scripts so that older settings can be imported into newer versions of the plugin.

If you want a snippet of code in your theme that sets up the options you have two recommended options: 
1. `option_bcn_options` if you want to always override the options set in the admin page
2. `bcn_settings_init` if you want to setup defaults that can be overridden in the admin page

Lastly, if you really want to modify an array of strings (or something close), you can: 
1. Set the first parameter to `true` when calling any of the `bcn_display` functions
2. You can call `bcn_display_json_ld(true);` and use PHP's JSON parser to get a object/array to play with

**Comment by decadence** [comment]
Thanks for the detailed answer.
I don't want to override all admin settings. I just want control breadcrumbs layout from php file.
`bcn_display_json_ld` is almost what I want but it contains some redundant information.
It can be used but I prefer to have something cleaner like:
```php
[
    [
        "name" => "Page",
        "url" => "http://domain.com",
        "current" => false,
        "type" => "page", // "post", "custom-post", so on
    ],
    [
        "name" => "Child Page",
        "url" => "http://domain.com/child",
        "current" => true,
        "type" => "page",
    ]
]
```

**Comment by mtekk** [comment]
You don't have to override all of the admin settings, you can pick the ones you want. Known good defaults are merged in with what is passed in from `option_bcn_options`. Likewise with `bcn_settings_init`, you will start with a full array of known good defaults and you only have to change the ones you want.

Regarding `bcn_display_json_ld()`, it outputs JSON-LD formatted Schema.org BreadcrumbList compliant JSON, hence the extra stuff. It should not be difficult to have you parser ignore the extra stuff.

**Comment by decadence** [comment]
Yes, `bcn_display_json_ld` is option.
Is there any problem with making `$breadcrumb_navxt->breadcrumb_trail` public for access to `$breadcrumb_navxt->breadcrumb_trail->breadcrumbs` array?

**Comment by mtekk** [comment]
I'm reluctant to make it accessible through the `breadcrumb_navxt` class given there are already other ways to interact with the `bcn_breadcrumb_trail` class. These include:

1. Directly instantiating `bcn_breadcrumb_trail`
2. Swapping out the `bcn_breadcrumb_trail` instance with your own using the `bcn_breadcrumb_trail_object` filter
3. Accessing through the `bcn_after_fill` action. The fully populated instance of the `bcn_breadcrumb_trail` object is passed by reference through this

Additionally, given what you have outlined thus far for your use case (unless I am missing something), I can think of several solutions to it that do not involve adding direct access to the `breadcrumb-navxt` class' `bcn_breadcrumb_trail` object.

**Comment by decadence** [comment]
Ok thanks
