### ISSUE TITLE
(Custom) Default Template with no anchor

### ISSUE THREAD

**Issue by lakyller** [mtekk/Breadcrumb-NavXT#193]
Hi,
How can I make/use (my) custom default template for "default_template_no_anchor" if the field for (example) Search Template (not linked) is empty in admin?

Thank you

**Comment by mtekk** [comment]
Can you elaborate on what you mean by using your custom default template for "default_template_no_anchor"?

**Comment by lakyller** [comment]
I'll try.

I made custom template with filter "bcn_breadcrumb_template_no_anchor" only for tag and search pages.
And it works only if  the field in admin is not empty (has a value).
If the field/textarea (Hsearch_template) is empty my custom template is not used.

Thank you

**Comment by mtekk** [comment]
I'm not exactly sure I completely understand you. Normally, you would just set the template in the settings page to be what you want. If you want it to be blank with something else setting that, it sounds like you are tying to set default values for the breadcrumb templates via code. To do that, you can use the `bcn_settings_init` filter and modify the settings as you see appropriate. I suggest setting the priority to a value greater than 11 (e.g. 12), so that it runs after other plugins that may change the settings. This will become the default is the setting for the template isn't set in the settings page.

**Comment by lakyller** [comment]
Thank you for respond. Solved.
