### ISSUE TITLE
bcn_pick_post_term not working with custom taxonomy

### ISSUE THREAD

**Issue by jq-87** [mtekk/Breadcrumb-NavXT#237]
```
function test(){
  $term = get_term(22, 'my_taxonomy');
  return $term;
}
add_filter('bcn_pick_post_term', 'test', 10);
```

The above snippet does not throw an error but the breadcrumbs does not output any term link.

Is there a way to make `bcn_pick_post_term` work with a custom taxonomy?

**Comment by mtekk** [comment]
It currently works with custom taxonomies. However, you are not allowed to pick a taxonomy within the filter that is different than the taxonomy of the term being filtered. Hence, there is a fourth parameter to the filter that is the taxonomy that is expected.

**Comment by jq-87** [comment]
@mtekk thank you, I got what I needed by using the plugin settings.

But I still have a question - under post types settings for the plugin: 
When setting "[POST_TYPE] Hierarchy" to something other than `Category` `bcn_pick_post_term` stops working for that post type - I imagine this is by design correct?

So if I wanted to change the "[POST_TYPE] Hierarchy" programmatically 
 to do something in `bcn_pick_post_term` how would I do that? I tried returning 'my_taxonomy' for my POST_TYPE in the `bcn_default_hierarchy_type` filter but `bcn_pick_post_term` still told me `category` was the active taxonomy.

Here's what I am trying:
```
function test2($taxonomy, $type){
  $taxonomy = 'my_taxonomy';
  return $taxonomy;
}
add_filter('bcn_default_hierarchy_type', 'test2', 100, 2);

function test($term, $id, $type, $taxonomy){
  var_dump($taxonomy); // still CATEGORY - expected my_taxonomy
  return $term;
}
add_filter('bcn_pick_post_term', 'test', 100, 4);
```

**Comment by mtekk** [comment]
As long as the Hierarchy type you chose is a hierarchical taxonomy, the `bcn_pick_post_term` filter should apply. Since for non-hierarchical taxonomies all the terms for that taxonomy are included in the breadcrumb trail, selecting a term to display doesn't really make sense.

The `bcn_default_hierarchy_type` is only used when initializing the settings for custom post types. If you have changed the settings, this filter will no longer have an effect.

Rather than introduce a new filter, in the next version (6.5), I'm going to change what taxonomy gets passed into `term_parents`, it will now be the taxonomy from the term being passed in. This will allow `bcn_pick_post_term` to change the taxonomy. Eventually, the internal API is going to change to passing a term instance into that function (has to wait for 7.0 due to API guarantees).

**Comment by mtekk** [comment]
I'm going to split this into two issues #240 which will have the more major change in v7.0 and #241 with the intermediate solution for v6.5.
