### ISSUE TITLE
bcn_display, parameter $force

### ISSUE THREAD

**Issue by gaspas** [mtekk/Breadcrumb-NavXT#279]
It's supposed that the four parameter true, bcn_display(false, true, false, true), force generation of the breadcrumb ignoring internal caching.  Like described here https://wordpress.org/support/topic/breadcrumbs-in-search-results/

But I already tested in 2 different sites and the results are not the expected, it always show the search results page as current.

Its inside the loop, it shows each result title, excerpt, thumbnail, etc but bcn_display seems to ignore $force = true? 

Did I miss something? 

I'am using WP 5.9.3 and Breadcrumb NavXT 7.0.2

Thanks

**Comment by mtekk** [comment]
There was a bug in bcn_breadcrumb_navxt::display() which was fixed in 7.3.1, specifically 1d82dc3 fixed this (#299 was a related issue which was fixed with the same commit).

**Comment by mtekk** [comment]
A little bit of clarification here, the `$force` parameter does bypass any internal breadcrumb trail caching, that said, if you're within a loop, older versions of Breadcrumb NavXT would try to generate the trail for the page holding the loop rather than any posts within the loop. Indirectly, as of 7.3, the `$force` parameter can influence this behavior (setting to true will generate the breadcrumb trail for the posts within the loop).
